services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: go_backend_postgres
    environment:
      POSTGRES_DB: go_backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abdullah
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - go_backend_network

  # Go Backend Application
  app:
    build: .
    container_name: go_backend_app
    environment:
      PORT: 8081
      DATABASE_URL: postgres://postgres:abdullah@postgres:5432/go_backend_db?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - go_backend_network

volumes:
  postgres_data:

networks:
  go_backend_network:
    driver: bridge
